apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    capabilities: Basic Install
  name: tektoncd-operator.v0.0.1
  namespace: tekton-pipelines
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - kind: Setup
      displayName: setup
      description: custom resource to trigger install
      name: setups.tekton.dev
      version: v1alpha1
  description: Placeholder description
  displayName: Tektoncd Operator
  install:
    spec:
      clusterPermissions:
      - rules:
        - apiGroups:
          - ""
          resources:
          - pods
          - services
          - endpoints
          - persistentvolumeclaims
          - events
          - configmaps
          - secrets
          verbs:
          - '*'
        - apiGroups:
          - ""
          resources:
          - namespaces
          verbs:
          - get
        - apiGroups:
          - apps
          resources:
          - deployments
          - daemonsets
          - replicasets
          - statefulsets
          verbs:
          - '*'
        - apiGroups:
          - monitoring.coreos.com
          resources:
          - servicemonitors
          verbs:
          - get
          - create
        - apiGroups:
          - tekton.dev
          resources:
          - '*'
          verbs:
          - '*'
        serviceAccountName: tektoncd-operator
      deployments:
      - name: tektoncd-operator
        spec:
          replicas: 1
          selector:
            matchLabels:
              name: tektoncd-operator
          strategy: {}
          template:
            metadata:
              labels:
                name: tektoncd-operator
            spec:
              containers:
              - command:
                - tektoncd-operator
                env:
                - name: WATCH_NAMESPACE
                - name: POD_NAME
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.name
                - name: OPERATOR_NAME
                  value: tektoncd-operator
                image: nikhilvep/tektoncd-operator:v0.0.1
                imagePullPolicy: Always
                name: tektoncd-operator
                resources: {}
              serviceAccountName: tektoncd-operator
    strategy: deployment
  installModes:
  - supported: true
    type: OwnNamespace
  - supported: true
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  maturity: alpha
  provider: {}
  version: 0.0.1
