cr-manifest: "deploy/crds/tekton_v1alpha1_install_cr.yaml"
init-timeout: 60
csv-path: "deploy/olm-catalog/tektoncd-pipeline-operator/0.0.1/tektoncd-pipeline-operator.v0.0.1.clusterserviceversion.yaml"

