apiVersion: tekton.dev/v1alpha1
kind: ClusterTask
metadata:
  name: buildah-v0-8-0
spec:
  inputs:
    params:
    - default: quay.io/buildah/stable
      description: The location of the buildah builder image.
      name: BUILDER_IMAGE
      type: string
    - default: ./Dockerfile
      description: Path to the Dockerfile to build.
      name: DOCKERFILE
      type: string
    - default: "true"
      description: Verify the TLS on the registry endpoint (for push/pull to a non-TLS
        registry)
      name: TLSVERIFY
      type: string
    resources:
    - name: source
      type: git
  outputs:
    resources:
    - name: image
      outputImageDir: /builder/home/image-outputs/image
      type: image
  steps:
  - command:
    - buildah
    - bud
    - --tls-verify=$(inputs.params.TLSVERIFY)
    - --layers
    - -f
    - $(inputs.params.DOCKERFILE)
    - -t
    - $(outputs.resources.image.url)
    - .
    image: $(inputs.params.BUILDER_IMAGE)
    name: build
    resources: {}
    securityContext:
      privileged: true
    volumeMounts:
    - mountPath: /var/lib/containers
      name: varlibcontainers
    workingDir: /workspace/source
  - command:
    - buildah
    - push
    - --tls-verify=$(inputs.params.TLSVERIFY)
    - $(outputs.resources.image.url)
    - docker://$(outputs.resources.image.url)
    image: $(inputs.params.BUILDER_IMAGE)
    name: push
    resources: {}
    securityContext:
      privileged: true
    volumeMounts:
    - mountPath: /var/lib/containers
      name: varlibcontainers
    workingDir: /workspace/source
  volumes:
  - emptyDir: {}
    name: varlibcontainers
