apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    capabilities: Basic Install
    alm-examples: |
      [
        {
          "apiVersion": "tekton.dev/v1alpha1",
          "kind": "Install",
          "metadata": {
            "name": "example-install",
            "namespace": "tekton-pipelines"
        },
          "spec": {}
        }
      ]
  name: tektoncd-pipeline-operator.v0.3.1
  namespace: tekton-pipelines
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - name: installs.tekton.dev
      version: v1alpha1
      kind: Install
      displayName: TektonCD-Pipeline Install
      description: CRD to trigger install/delete of TektonCD-Pipeline
      resources:
      - kind: Pod
        version: v1
      - kind: Service
        version: v1
      - kind: ServiceAccount
        version: v1
      - kind: ConfigMap
        version: v1
      specDescriptors: []
      statusDescriptors:
      - description: List of resources installed by the operator for this cr
        displayName: Installed Resources
        path: resources
      - description: Version of Tektoncd Pipeline installed
        displayName: Tektoncd Pipeline Version
        path: version
  description: Tektoncd Operator Cluster Service Version
  displayName: Tektoncd Operator
  install:
    spec:
      clusterPermissions:
      - rules:
        - apiGroups:
          - ""
          resources:
          - pods
          - services
          - endpoints
          - persistentvolumeclaims
          - events
          - configmaps
          - secrets
          verbs:
          - '*'
        - apiGroups:
          - ""
          resources:
          - namespaces
          verbs:
          - get
          - list
          - create
          - update
          - delete
          - patch
          - watch
        - apiGroups:
          - apps
          resources:
          - deployments
          - daemonsets
          - replicasets
          - statefulsets
          - deployments/finalizers
          verbs:
          - '*'
        - apiGroups:
          - monitoring.coreos.com
          resources:
          - servicemonitors
          verbs:
          - get
          - create
        - apiGroups:
          - tekton.dev
          resources:
          - '*'
          - installs
          verbs:
          - '*'
        - apiGroups:
          - rbac.authorization.k8s.io
          resources:
          - clusterroles
          verbs:
          - get
          - create
          - update
          - delete
        - apiGroups:
          - ""
          resources:
          - serviceaccounts
          verbs:
          - get
          - list
          - create
          - update
          - delete
          - patch
          - watch
        - apiGroups:
          - rbac.authorization.k8s.io
          resources:
          - clusterrolebindings
          verbs:
          - get
          - create
          - update
          - delete
        - apiGroups:
          - apiextensions.k8s.io
          resources:
          - customresourcedefinitions
          verbs:
          - get
          - create
          - update
          - delete
        - apiGroups:
          - admissionregistration.k8s.io
          resources:
          - mutatingwebhookconfigurations
          verbs:
          - get
          - list
          - create
          - update
          - delete
          - patch
          - watch
        - apiGroups:
          - build.knative.dev
          resources:
          - builds
          - buildtemplates
          - clusterbuildtemplates
          verbs:
          - get
          - list
          - create
          - update
          - delete
          - patch
          - watch
        - apiGroups:
          - extensions
          resources:
          - deployments
          verbs:
          - get
          - list
          - create
          - update
          - delete
          - patch
          - watch
        - apiGroups:
          - extensions
          resources:
          - deployments/finalizers
          verbs:
          - get
          - list
          - create
          - update
          - delete
          - patch
          - watch
        - apiGroups:
          - policy
          resources:
          - podsecuritypolicies
          verbs:
          - get
          - create
          - update
          - use
        serviceAccountName: tektoncd-pipeline-operator
      deployments:
      - name: tektoncd-pipeline-operator
        spec:
          replicas: 1
          selector:
            matchLabels:
              name: tektoncd-pipeline-operator
          strategy: {}
          template:
            metadata:
              labels:
                name: tektoncd-pipeline-operator
            spec:
              containers:
              - command:
                - tektoncd-pipeline-operator
                env:
                - name: WATCH_NAMESPACE
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.namespace
                - name: POD_NAME
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.name
                - name: OPERATOR_NAME
                  value: tektoncd-pipeline-operator
                image: quay.io/openshift-pipeline/tektoncd-pipeline-operator:v0.3.1-2
                imagePullPolicy: Always
                name: tektoncd-pipeline-operator
                resources: {}
              serviceAccountName: tektoncd-pipeline-operator
    strategy: deployment
  installModes:
  - supported: true
    type: OwnNamespace
  - supported: true
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  maturity: alpha
  provider: {}
  version: 0.3.1
