kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: tektoncd-pipeline-operator
subjects:
- kind: ServiceAccount
  name: tektoncd-pipeline-operator
  # Replace this with the namespace the operator is deployed in.
  namespace: tekton-pipelines
roleRef:
  kind: ClusterRole
  name: tektoncd-pipeline-operator
  apiGroup: rbac.authorization.k8s.io
