apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: '[{"apiVersion":"tekton.dev/v1alpha1","kind":"Install","metadata":{"name":"example-install","namespace":"openshift-pipelines-operator"},"spec":{}}]'
    capabilities: Basic Install
    categories: "Developer Tools, Integration & Delivery"
    description: OpenShift Pipelines is a cloud-native CI/CD solution for building pipelines using Tekton concepts which run natively on OpenShift and Kubernetes.
    containerImage: quay.io/openshift-pipeline/openshift-pipelines-operator:v0.4.0-1
    createdAt: 2019-03-15T19:44:21Z
    certified: "false"
    support: Red Hat, Inc.
    repository: https://github.com/openshift/tektoncd-pipeline-operator
  name: openshift-pipelines-operator.v0.4.0
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - kind: Install
      name: installs.tekton.dev
      version: v1alpha1
      displayName: OpenShift Pipelines Install
      description: OpenShift Pipelines is a cloud-native CI/CD solution for building pipelines using Tekton concepts which run natively on OpenShift and Kubernetes.
      resources:
      - kind: clusterroles
        version: v1
      - kind: customresourcedefinitions
        version: v1beta1
      - kind: deployments
        version: v1beta1
      - kind: podsecuritypolicies
        version: v1beta1
      - kind: clusterrolebindings
        version: v1beta1
      - kind: services
        version: v1
      - kind: pods
        version: v1
      - kind: configmaps
        version: v1
      - kind: installs
        version: v1alpha1
      - kind: namespaces
        version: v1
      - kind: serviceaccounts
        version: v1
      specDescriptors: []
      statusDescriptors:
      # - description: List of resources installed by the operator for this cr
      #   displayName: Installed Resources
      #   path: resources
      - description: Version of Tekton Pipeline installed
        displayName: Tekton Pipeline Version
        path: version
  description: |
    # OpenShift Pipelines
    OpenShift Pipelines is a cloud-native continuous integration and delivery (CI/CD) solution for building pipelines using [Tekton](https://tekton.dev). Tekton is a flexible Kubernetes-native open-source CI/CD framework which enables automating deployments across multiple platforms (Kubernetes, serverless, VMs, etc) by abstracting away the underlying details. 

    ## Features
    * Standard CI/CD pipelines definition
    * Build images with Kubernetes tools such as S2I, Buildah, Buildpacks, Kaniko, etc
    * Deploy applications to multiple platforms such as Kubernetes, serverless and VMs
    * Easy to extend and integrate with existing tools
    * Scale pipelines on-demand
    * Portable across any Kubernetes platform
    * Designed for microservices and decentralised team
    * Integrated with OpenShift Developer Console

    ## Installation
    _OpenShift Pipelines Operator_ gets installed into a single namespace which would then install _OpenShift Pipelines_ into the same namespace. _OpenShift Pipelines_ is however cluster-wide and can run pipelines created in any namespace.

    #### Pre-Requisites
    none

    ## Getting Started
    In order to get familiar with _OpenShift Pipelines_ concepts and create your first pipeline, follow the [OpenShift Pipelines Tutorial](https://github.com/openshift/pipelines-tutorial).

    ### CLI
    Tekton Pipelines cli project provides a CLI for interacting with Openshift Pipelines.

    [Download Tekton CLI](https://github.com/tektoncd/cli/releases/tag/v0.1.0)

    [Tekton CLI Project](https://github.com/tektoncd/cli)
  displayName: OpenShift Pipelines Operator  
  install:
    spec:
      clusterPermissions:
      - rules:
        - apiGroups:
          - ""
          resources:
          - pods
          - services
          - endpoints
          - persistentvolumeclaims
          - events
          - configmaps
          - secrets
          - pods/log
          verbs:
          - '*'
        - apiGroups:
          - ""
          resources:
          - namespaces
          verbs:
          - get
          - list
          - create
          - update
          - delete
          - patch
          - watch
        - apiGroups:
          - apps
          resources:
          - deployments
          - daemonsets
          - replicasets
          - statefulsets
          - deployments/finalizers
          verbs:
          - '*'
        - apiGroups:
          - monitoring.coreos.com
          resources:
          - servicemonitors
          verbs:
          - get
          - create
          - delete
        - apiGroups:
          - tekton.dev
          resources:
          - '*'
          - installs
          verbs:
          - '*'
        - apiGroups:
          - rbac.authorization.k8s.io
          resources:
          - clusterroles
          verbs:
          - get
          - create
          - update
          - delete
        - apiGroups:
          - ""
          resources:
          - serviceaccounts
          verbs:
          - get
          - list
          - create
          - update
          - delete
          - patch
          - watch
        - apiGroups:
          - rbac.authorization.k8s.io
          resources:
          - clusterrolebindings
          verbs:
          - get
          - create
          - update
          - delete
        - apiGroups:
          - apiextensions.k8s.io
          resources:
          - customresourcedefinitions
          verbs:
          - get
          - create
          - update
          - delete
        - apiGroups:
          - admissionregistration.k8s.io
          resources:
          - mutatingwebhookconfigurations
          verbs:
          - get
          - list
          - create
          - update
          - delete
          - patch
          - watch
        - apiGroups:
          - build.knative.dev
          resources:
          - builds
          - buildtemplates
          - clusterbuildtemplates
          verbs:
          - get
          - list
          - create
          - update
          - delete
          - patch
          - watch
        - apiGroups:
          - extensions
          resources:
          - deployments
          verbs:
          - get
          - list
          - create
          - update
          - delete
          - patch
          - watch
        - apiGroups:
          - extensions
          resources:
          - deployments/finalizers
          verbs:
          - get
          - list
          - create
          - update
          - delete
          - patch
          - watch
        - apiGroups:
          - policy
          resources:
          - podsecuritypolicies
          verbs:
          - get
          - create
          - update
          - delete
          - use
        serviceAccountName: openshift-pipelines-operator
      deployments:
      - name: openshift-pipelines-operator
        spec:
          replicas: 1
          selector:
            matchLabels:
              name: openshift-pipelines-operator
          strategy: {}
          template:
            metadata:
              labels:
                name: openshift-pipelines-operator
            spec:
              containers:
              - command:
                - openshift-pipelines-operator
                env:
                - name: WATCH_NAMESPACE
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.annotations['olm.targetNamespaces']
                - name: POD_NAME
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.name
                - name: OPERATOR_NAME
                  value: openshift-pipelines-operator
                image: quay.io/openshift-pipeline/openshift-pipelines-operator:v0.4.0-1
                imagePullPolicy: Always
                name: openshift-pipelines-operator
                resources: {}
              serviceAccountName: openshift-pipelines-operator
    strategy: deployment
  installModes:
  - supported: true
    type: OwnNamespace
  - supported: true
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: false
    type: AllNamespaces
  maturity: alpha
  provider:
    name: Red Hat, Inc.
  version: 0.4.0
  replaces: openshift-pipelines-operator.v0.3.1
  maintainers:
  - name: Red Hat, Inc.
    email: customerservice@redhat.com
  links:
  - name: Openshift Tektoncd Pipeline GitHub Repository
    url: https://github.com/openshift/tektoncd-pipeline
  - name: OpenShift Pipelines Operator GitHub Repository
    url: https://github.com/openshift/tektoncd-pipeline-operator
  icon:
  - base64data: iVBORw0KGgoAAAANSUhEUgAAACgAAAAoCAYAAACM/rhtAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAAF6AAABegB0iYb4wAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAAAb1SURBVFiFvZhtUFTXGcd/5967u7AsgrwJCAsJkShopxRETZykTMzEpEma2oZxjNOaSaztCNOWmdS2JG0nTWteOm2M0Wn6wcbGtnY0jcnEmIklL9WkChqoUkAIFgRW5H1537d7+gENLLvc3TXq/9s9z/Oc53fPPefc5xzBVUiC2pRFMTolQCGCxUAaYLvsMgo4kJwDTkuV95e0US1AjzSXiMT5bDqZJo2tEjYCCyPM1Qns03zsWtRF5zUFbEkl2WvmGWATYI4QbLbcEvaoXp661UHfFwZszGIDkp1AwhcEm61+KSnL62C/kdOcgKcKMdl62S3h8WsMNluvjCVTXnQaTzBjUMBT6VitKgeF4N7ry/Y5xDujGhuKzuMMYpsFV4jJ2sObNwoOYEwHt2QgLp6s/P8yOtOmzHa29bL7RsON6+CVJIw4OTnb7jeCTVk8IiX7wu5dVYlZVULMnfcQtawQLTkVYbbgGxrA3drE+OlPGHnndXz9PYZwM2WBl1c4KA8AbFxIIipNQFJIMEUhfv3jJH7vx5iycgxdpcfNyOED9D73UzyODkO4y0AyVrD4y100w8xPrPKbcOBM6Xbs+z8gdfsrIeEAhMnMvIce4aaqRuJKHzWEA5AgJiX/mAEMLQvJ8Kq0EmITNucsxv6Xo2hpGSHB5tLFnb/ms2efDOkXY2ZVYRsnNACfSlkoODUhaU4417l6Ro++hau5HunzoSUkY129Btud9yCiov1808orGb/UjePNvyPyC5DH3guaz+vh98AqIUFpstMOGA5LxquHsZXc599JdxcXt21m7KN3QcqgL5W8bTvx66f2evewk/Z/VTHgdIKuY4m2MrlvN56a4wGxCvjmO7BqTVmsQBrDxXx1bQDc5JlTdGy6D19/75xxvoE+urdtZvDfH+HWJX2fVhP1WAW2pQWgKLg//ie6czBorA6qK5ONGjolof7ISeX+c8bb203n5ocM4a5oTIfeg1M7l1BVLBdaGD/+HpMfHgHXpGGs18fDGlBk5GRKtxNdeJtfW9/vfoG3uyssuHEdrLfmk3z/wywo3YQlI4umrRuYDAEH4BMs0xDkGjlZV98FYnqIfYP9OA/uDRsOIOfpHcSvvutzW8o3N9J76G8h+9AliQpTlfCcsuQu9XueqDuJ7vWAJSosOIBL+/f42ed9ZWVIOAAdLArTZXpQqQnTe/dgfS3nm5sZfu7PeG/JCwsOwHnymN+zEhNL9JoHsP3sBZSkBXPmliC0EC+Bt+ciA3/8LW2WWIRmwrwgndicJYi4wPp1rj+E6/J8HTlbi6O1BW9qBtZtzyLcLib2vGiYXzTa6SeMaln+chfyljzEh4cRVW/B/5rDgrsia24ebtVE3Iv7sPQ6iFUVEgqKOVmQhj4xHhwOpAZcNAJUrDHErl2Hpkj6v7MGfL4An1BwAOPNDaRs3MJNKYmYl07Na1dn+5xwAAq4NCTNCPJnG9XEFFIqXyB27TqUGBvS68H50q/w9l2KGA6migb7lgrMKdNrcuh4lWGMIuhXgFPBjProMLa7H0SJmVpDQjMxf3PFVcEBZHz/CaJv9t/Ret74q2GMKjijSJX3gxmla5KRI6/7tSU89kOiC1ZCciqu+zcwGR0bFlzy19eT/cTTfm0jdTUMffKBcaDggJCgnLPTJiFztt2Ukc3NVQ2IqGi8I056Txxj2OXGl50LioJS/ykTe3cyWlcdtH81dh72H/2cjO9W+G326Dp1D6xkpK5mTjYFfLc7iBIAjXa2Az8J5hhX+ijS5WKk+hi+5/ei2mKJGewjPtOOLTcPpGS45mP63z3EeEsjuseNeUEa84puJ/nBUrS4+QF9tj//FBd2PGM4eGbBiZVdrIqoYPXk5JH72hEsC+2GnRvJ8aeXaX2yPKRflEpxcQc1CsCiLjol7DEKGNNh6FwD/1l3B6P1tRGD6a5JWivLwoIzC84Wd1ADM84kUqcSgt+VzFytrs526r5WTGtlGZ6+4Kc1fzKdvrcPUHtvEY5Xd4V0FyCj4FsznqfVkMl6IfArM4y2EqFpxN9xN0lrv4F10RKisqcOUV7nEJPtrQwdr2Lg6NtMtH0W+kUuKwpeKnbwg6CAAI12/gBsCQV3PWQR1K/oYtnMtoCbhcUX2CoEh240nAl6xrtYPrs9AFCAb1Rlk1sndD1/jaRBjwnySyCgzA4ABCg6j9OcRrZZoeF6w1kE9S4HWUVzXGaGvMCszmCHS6dcRnhdHEoq6GaVHcs7qDDyCyvpiQwWofOGm8Cq52pkFpzVBetu6yTk8o5oVE5mUoTOTo9kuQ5qJLEK+DRBjVWl7EsXOB1u3FV9NglabSbfdvsolYKluiRRB8uVaSBAKuBSBP2q4AyCA8s7eE2AN9Jc/wfeEJ7J7W1cPAAAAABJRU5ErkJggg==
    mediatype: image/png
  keywords: ['tektoncd', 'openshift', 'build', 'pipeline']
