apiVersion: tekton.dev/v1alpha1
kind: ClusterTask
metadata:
  name: openshift-client-v0-8-0
spec:
  inputs:
    params:
    - default:
      - help
      description: The OpenShift CLI arguments to run
      name: ARGS
      type: array
  steps:
  - args:
    - $(inputs.params.ARGS)
    command:
    - /usr/bin/oc
    image: quay.io/openshift/origin-cli:latest
    name: oc
    resources: {}
